import {
  District,
  HeatmapResponse,
  LandslideReport,
  Alert,
  AlertTemplate,
  OverviewStats,
  PriorityVillageItem,
  RoadSegment,
  RiskHeatmapPoint,
} from '../types';

export const mockDistricts: District[] = [
  {
    id: 'IN-ML-EKH',
    name: 'East Khasi Hills (Shillong)',
    state: 'Meghalaya',
    latitude: 25.5788,
    longitude: 91.8933,
    population: 825922,
    areaSqKm: 2748.0,
    emergencyHelpline: '1077 / 0364-2222277',
    dmaControlRoomContact: '+91 364 2501234',
    currentRainfall24h: 78.5,
    cumulativeRainfall3d: 215.0,
    cumulativeRainfall7d: 440.0,
    currentRiskLevel: 'HIGH',
    triggerStatus: 'WARNING',
  },
  {
    id: 'IN-AS-DH',
    name: 'Dima Hasao (Haflong)',
    state: 'Assam',
    latitude: 25.1833,
    longitude: 93.0167,
    population: 214102,
    areaSqKm: 4888.0,
    emergencyHelpline: '1077 / 03673-236222',
    dmaControlRoomContact: '+91 3673 236100',
    currentRainfall24h: 112.0,
    cumulativeRainfall3d: 320.0,
    cumulativeRainfall7d: 610.0,
    currentRiskLevel: 'VERY_HIGH',
    triggerStatus: 'ALERT',
  },
  {
    id: 'IN-SK-GTK',
    name: 'Gangtok',
    state: 'Sikkim',
    latitude: 27.3389,
    longitude: 88.6065,
    population: 281293,
    areaSqKm: 954.0,
    emergencyHelpline: '1070 / 03592-202720',
    dmaControlRoomContact: '+91 3592 202111',
    currentRainfall24h: 45.0,
    cumulativeRainfall3d: 120.0,
    cumulativeRainfall7d: 250.0,
    currentRiskLevel: 'MODERATE',
    triggerStatus: 'WATCH',
  },
  {
    id: 'IN-MZ-CHM',
    name: 'Champhai',
    state: 'Mizoram',
    latitude: 23.4750,
    longitude: 93.3280,
    population: 125745,
    areaSqKm: 3185.0,
    emergencyHelpline: '1077 / 03831-234200',
    dmaControlRoomContact: '+91 3831 234111',
    currentRainfall24h: 32.0,
    cumulativeRainfall3d: 95.0,
    cumulativeRainfall7d: 180.0,
    currentRiskLevel: 'LOW',
    triggerStatus: 'NORMAL',
  },
  {
    id: 'IN-NL-KHM',
    name: 'Kohima',
    state: 'Nagaland',
    latitude: 25.6701,
    longitude: 94.1077,
    population: 267988,
    areaSqKm: 1463.0,
    emergencyHelpline: '1077 / 0370-2290022',
    dmaControlRoomContact: '+91 370 2290011',
    currentRainfall24h: 54.0,
    cumulativeRainfall3d: 145.0,
    cumulativeRainfall7d: 290.0,
    currentRiskLevel: 'HIGH',
    triggerStatus: 'WARNING',
  },
];

export const mockVillages: PriorityVillageItem[] = [
  {
    id: 1,
    name: 'Cherrapunji (Sohra) Rim',
    districtId: 'IN-ML-EKH',
    latitude: 25.2986,
    longitude: 91.7203,
    population: 11722,
    vulnerabilityIndex: 0.88,
    nearestShelterName: 'Sohra Community Hall Shelter',
    nearestShelterDistKm: 1.2,
    evacuationRoute: 'North via Sohra-Shella Road to Highland Relief Camp 1',
    compositeRiskScore: 0.82,
    riskLevel: 'VERY_HIGH',
    priorityScore: 8450.0,
  },
  {
    id: 2,
    name: 'Mawsynram Khas',
    districtId: 'IN-ML-EKH',
    latitude: 25.2974,
    longitude: 91.5828,
    population: 6420,
    vulnerabilityIndex: 0.85,
    nearestShelterName: 'Mawsynram Higher Secondary School',
    nearestShelterDistKm: 0.8,
    evacuationRoute: 'East toward Mawsynram Block HQ via Ridge Highway',
    compositeRiskScore: 0.79,
    riskLevel: 'HIGH',
    priorityScore: 4310.0,
  },
  {
    id: 3,
    name: 'Pynursla Ridge Sector',
    districtId: 'IN-ML-EKH',
    latitude: 25.3090,
    longitude: 91.8950,
    population: 4850,
    vulnerabilityIndex: 0.78,
    nearestShelterName: 'Pynursla BDO Complex',
    nearestShelterDistKm: 1.5,
    evacuationRoute: 'North toward Smit via Bypass',
    compositeRiskScore: 0.71,
    riskLevel: 'HIGH',
    priorityScore: 2680.0,
  },
  {
    id: 4,
    name: 'Haflong Hill Cut Colony',
    districtId: 'IN-AS-DH',
    latitude: 25.1667,
    longitude: 93.0167,
    population: 14500,
    vulnerabilityIndex: 0.92,
    nearestShelterName: 'Haflong Govt College Ground',
    nearestShelterDistKm: 1.0,
    evacuationRoute: 'Upward toward Circuit House Hilltop via Fiangpui bypass',
    compositeRiskScore: 0.88,
    riskLevel: 'VERY_HIGH',
    priorityScore: 11720.0,
  },
  {
    id: 5,
    name: 'Jatinga Pass Ridge',
    districtId: 'IN-AS-DH',
    latitude: 25.1200,
    longitude: 93.0400,
    population: 3200,
    vulnerabilityIndex: 0.90,
    nearestShelterName: 'Jatinga High School Shelter',
    nearestShelterDistKm: 0.6,
    evacuationRoute: 'Immediate retreat to Jatinga High Ridge Shelter',
    compositeRiskScore: 0.91,
    riskLevel: 'VERY_HIGH',
    priorityScore: 2620.0,
  },
  {
    id: 6,
    name: 'Harangajao Valley Toe',
    districtId: 'IN-AS-DH',
    latitude: 25.1050,
    longitude: 92.8650,
    population: 5400,
    vulnerabilityIndex: 0.95,
    nearestShelterName: 'Harangajao Railway Station Hall',
    nearestShelterDistKm: 0.4,
    evacuationRoute: 'Evacuate valley floor towards Upper Harangajao Railway Yard',
    compositeRiskScore: 0.94,
    riskLevel: 'VERY_HIGH',
    priorityScore: 4830.0,
  },
  {
    id: 7,
    name: 'Tadong Valley Ward',
    districtId: 'IN-SK-GTK',
    latitude: 27.3150,
    longitude: 88.5980,
    population: 8900,
    vulnerabilityIndex: 0.65,
    nearestShelterName: 'Sikkim University Indoor Stadium',
    nearestShelterDistKm: 1.1,
    evacuationRoute: 'Upper ridge road toward 5th Mile junction',
    compositeRiskScore: 0.58,
    riskLevel: 'MODERATE',
    priorityScore: 3350.0,
  },
  {
    id: 8,
    name: 'Naga Bazaar Slope Area',
    districtId: 'IN-NL-KHM',
    latitude: 25.6750,
    longitude: 94.1020,
    population: 7600,
    vulnerabilityIndex: 0.82,
    nearestShelterName: 'Kohima Local Ground Community Hall',
    nearestShelterDistKm: 0.9,
    evacuationRoute: 'Ascend toward Secretariat Road via High School junction',
    compositeRiskScore: 0.77,
    riskLevel: 'HIGH',
    priorityScore: 4800.0,
  },
];

export const mockRoadSegments: RoadSegment[] = [
  {
    id: 1,
    roadNumber: 'NH-06',
    segmentName: 'Shillong - Jowai Ghat Cut Section',
    districtId: 'IN-ML-EKH',
    startLat: 25.5500,
    startLon: 91.9500,
    endLat: 25.4800,
    endLon: 92.1500,
    lengthKm: 28.5,
    criticalityIndex: 10,
    status: 'CAUTION',
    blockageCause: 'Multiple debris slips along cut slope km 34-38',
    alternateRouteAdvisory: 'Light vehicles only via Mawryngkneng bypass',
    currentHazardScore: 0.68,
  },
  {
    id: 2,
    roadNumber: 'SH-01',
    segmentName: 'Shillong - Pynursla - Dawki Corridor',
    districtId: 'IN-ML-EKH',
    startLat: 25.5200,
    startLon: 91.8800,
    endLat: 25.2000,
    endLon: 91.9200,
    lengthKm: 44.0,
    criticalityIndex: 8,
    status: 'CRITICAL',
    blockageCause: 'Tension cracks of 15cm width developed across both lanes at Wahkhen ghat',
    alternateRouteAdvisory: 'Heavy freight trucks diverted via Umkiang-Ratacherra',
    currentHazardScore: 0.85,
  },
  {
    id: 3,
    roadNumber: 'NH-27',
    segmentName: 'Haflong - Lumding Hill Section (E-W Corridor)',
    districtId: 'IN-AS-DH',
    startLat: 25.2000,
    startLon: 93.0200,
    endLat: 25.7500,
    endLon: 93.1800,
    lengthKm: 68.0,
    criticalityIndex: 10,
    status: 'BLOCKED',
    blockageCause: 'Massive mudslide over 120 meters at Dihangi; track and road submerged',
    alternateRouteAdvisory: 'All vehicular movement halted. NHIDCL earthmovers deployed.',
    currentHazardScore: 0.96,
  },
  {
    id: 4,
    roadNumber: 'NH-54E',
    segmentName: 'Jatinga - Harangajao Ghat Bypass',
    districtId: 'IN-AS-DH',
    startLat: 25.1200,
    startLon: 93.0400,
    endLat: 25.1000,
    endLon: 92.8600,
    lengthKm: 24.5,
    criticalityIndex: 9,
    status: 'BLOCKED',
    blockageCause: 'Bridge approach washed away by Flash debris flow near Migrendisa',
    alternateRouteAdvisory: 'Strict road closure by District Administration Dima Hasao',
    currentHazardScore: 0.98,
  },
  {
    id: 5,
    roadNumber: 'NH-10',
    segmentName: 'Sevoke - Gangtok Highway (29th Mile)',
    districtId: 'IN-SK-GTK',
    startLat: 27.1800,
    startLon: 88.5200,
    endLat: 27.3300,
    endLon: 88.6100,
    lengthKm: 32.0,
    criticalityIndex: 10,
    status: 'CAUTION',
    blockageCause: 'Periodic shooting stones and rolling boulders at 29th Mile',
    alternateRouteAdvisory: 'One-way traffic piloted by Border Roads Organisation (BRO)',
    currentHazardScore: 0.62,
  },
  {
    id: 6,
    roadNumber: 'NH-29',
    segmentName: 'Dimapur - Kohima 4-Lane Cut Section',
    districtId: 'IN-NL-KHM',
    startLat: 25.7800,
    startLon: 93.8800,
    endLat: 25.6800,
    endLon: 94.1000,
    lengthKm: 38.0,
    criticalityIndex: 10,
    status: 'CRITICAL',
    blockageCause: 'Active soil slump at Dzüdza bridge approach; 1 lane operational',
    alternateRouteAdvisory: 'Light motor vehicles diverted via Jotsoma bypass',
    currentHazardScore: 0.81,
  },
];

export const mockHeatmapPoints: RiskHeatmapPoint[] = [
  // East Khasi Hills (Shillong, Sohra, Mawsynram)
  { cellId: 'EKH-G101', latitude: 25.5788, longitude: 91.8933, staticScore: 0.52, staticClass: 'Moderate', compositeRiskScore: 0.64, compositeRiskLevel: 'HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 78.5, slopeAngleDeg: 34.2 },
  { cellId: 'EKH-G102', latitude: 25.2986, longitude: 91.7203, staticScore: 0.78, staticClass: 'High', compositeRiskScore: 0.88, compositeRiskLevel: 'VERY_HIGH', dynamicTriggerLevel: 'ALERT', rainfall1dMm: 112.4, slopeAngleDeg: 46.5 },
  { cellId: 'EKH-G103', latitude: 25.2974, longitude: 91.5828, staticScore: 0.75, staticClass: 'High', compositeRiskScore: 0.85, compositeRiskLevel: 'VERY_HIGH', dynamicTriggerLevel: 'ALERT', rainfall1dMm: 108.0, slopeAngleDeg: 42.1 },
  { cellId: 'EKH-G104', latitude: 25.3090, longitude: 91.8950, staticScore: 0.68, staticClass: 'High', compositeRiskScore: 0.74, compositeRiskLevel: 'HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 82.0, slopeAngleDeg: 38.0 },
  { cellId: 'EKH-G105', latitude: 25.5200, longitude: 91.8800, staticScore: 0.58, staticClass: 'Moderate', compositeRiskScore: 0.69, compositeRiskLevel: 'HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 74.0, slopeAngleDeg: 35.5 },
  { cellId: 'EKH-G106', latitude: 25.4800, longitude: 91.9800, staticScore: 0.42, staticClass: 'Moderate', compositeRiskScore: 0.48, compositeRiskLevel: 'MODERATE', dynamicTriggerLevel: 'WATCH', rainfall1dMm: 55.0, slopeAngleDeg: 28.0 },
  { cellId: 'EKH-G107', latitude: 25.6400, longitude: 91.8400, staticScore: 0.28, staticClass: 'Low', compositeRiskScore: 0.32, compositeRiskLevel: 'LOW', dynamicTriggerLevel: 'NORMAL', rainfall1dMm: 35.0, slopeAngleDeg: 19.5 },
  { cellId: 'EKH-G108', latitude: 25.3800, longitude: 91.7800, staticScore: 0.65, staticClass: 'High', compositeRiskScore: 0.76, compositeRiskLevel: 'HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 89.0, slopeAngleDeg: 39.8 },

  // Dima Hasao (Haflong, Jatinga, Harangajao)
  { cellId: 'DH-G201', latitude: 25.1833, longitude: 93.0167, staticScore: 0.84, staticClass: 'Very High', compositeRiskScore: 0.92, compositeRiskLevel: 'VERY_HIGH', dynamicTriggerLevel: 'ALERT', rainfall1dMm: 118.0, slopeAngleDeg: 48.0 },
  { cellId: 'DH-G202', latitude: 25.1200, longitude: 93.0400, staticScore: 0.89, staticClass: 'Very High', compositeRiskScore: 0.95, compositeRiskLevel: 'VERY_HIGH', dynamicTriggerLevel: 'ALERT', rainfall1dMm: 125.0, slopeAngleDeg: 52.3 },
  { cellId: 'DH-G203', latitude: 25.1050, longitude: 92.8650, staticScore: 0.86, staticClass: 'Very High', compositeRiskScore: 0.94, compositeRiskLevel: 'VERY_HIGH', dynamicTriggerLevel: 'ALERT', rainfall1dMm: 120.0, slopeAngleDeg: 49.1 },
  { cellId: 'DH-G204', latitude: 25.2800, longitude: 93.1200, staticScore: 0.72, staticClass: 'High', compositeRiskScore: 0.81, compositeRiskLevel: 'VERY_HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 95.0, slopeAngleDeg: 41.5 },
  { cellId: 'DH-G205', latitude: 25.3500, longitude: 93.1800, staticScore: 0.61, staticClass: 'Moderate', compositeRiskScore: 0.68, compositeRiskLevel: 'HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 78.0, slopeAngleDeg: 36.0 },

  // Gangtok (Sikkim)
  { cellId: 'GTK-G301', latitude: 27.3389, longitude: 88.6065, staticScore: 0.54, staticClass: 'Moderate', compositeRiskScore: 0.58, compositeRiskLevel: 'MODERATE', dynamicTriggerLevel: 'WATCH', rainfall1dMm: 45.0, slopeAngleDeg: 33.0 },
  { cellId: 'GTK-G302', latitude: 27.3150, longitude: 88.5980, staticScore: 0.62, staticClass: 'Moderate', compositeRiskScore: 0.65, compositeRiskLevel: 'HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 52.0, slopeAngleDeg: 37.8 },
  { cellId: 'GTK-G303', latitude: 27.3700, longitude: 88.6300, staticScore: 0.45, staticClass: 'Moderate', compositeRiskScore: 0.49, compositeRiskLevel: 'MODERATE', dynamicTriggerLevel: 'WATCH', rainfall1dMm: 41.0, slopeAngleDeg: 29.5 },

  // Champhai (Mizoram)
  { cellId: 'CHM-G401', latitude: 23.4750, longitude: 93.3280, staticScore: 0.35, staticClass: 'Low', compositeRiskScore: 0.38, compositeRiskLevel: 'LOW', dynamicTriggerLevel: 'NORMAL', rainfall1dMm: 32.0, slopeAngleDeg: 22.0 },
  { cellId: 'CHM-G402', latitude: 23.5200, longitude: 93.3500, staticScore: 0.40, staticClass: 'Moderate', compositeRiskScore: 0.42, compositeRiskLevel: 'MODERATE', dynamicTriggerLevel: 'WATCH', rainfall1dMm: 36.0, slopeAngleDeg: 26.5 },

  // Kohima (Nagaland)
  { cellId: 'KHM-G501', latitude: 25.6701, longitude: 94.1077, staticScore: 0.69, staticClass: 'High', compositeRiskScore: 0.78, compositeRiskLevel: 'HIGH', dynamicTriggerLevel: 'WARNING', rainfall1dMm: 54.0, slopeAngleDeg: 40.2 },
  { cellId: 'KHM-G502', latitude: 25.6950, longitude: 94.0850, staticScore: 0.74, staticClass: 'High', compositeRiskScore: 0.82, compositeRiskLevel: 'VERY_HIGH', dynamicTriggerLevel: 'ALERT', rainfall1dMm: 62.0, slopeAngleDeg: 43.5 },
  { cellId: 'KHM-G503', latitude: 25.6300, longitude: 94.1200, staticScore: 0.51, staticClass: 'Moderate', compositeRiskScore: 0.56, compositeRiskLevel: 'MODERATE', dynamicTriggerLevel: 'WATCH', rainfall1dMm: 48.0, slopeAngleDeg: 31.0 },
];

export const mockReports: LandslideReport[] = [
  {
    id: 1,
    latitude: 25.2980,
    longitude: 91.7210,
    locationDescription: 'NH-6 Km 45 near Cherrapunji, Meghalaya',
    districtId: 'IN-ML-EKH',
    landslideType: 'DEBRIS_FLOW',
    severity: 'CATASTROPHIC',
    description: 'Massive debris flow and mud slurry inundated 80 meters of highway pavement following 112mm torrential rainfall. Traffic halted.',
    reporterName: 'L. Kharkongor (SDRF East Khasi Hills)',
    reporterPhone: '+91 98620 11234',
    reporterRole: 'ROLE_FIELD_OFFICER',
    status: 'VERIFIED',
    verifiedBy: 'DDMA East Khasi Hills',
    timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
    roadBlocked: true,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-1.jpg',
  },
  {
    id: 2,
    latitude: 25.1850,
    longitude: 93.0210,
    locationDescription: 'NH-27 Dihangi Cut Section, Dima Hasao, Assam',
    districtId: 'IN-AS-DH',
    landslideType: 'SOIL_SLIDE',
    severity: 'CATASTROPHIC',
    description: 'Massive hillside collapse carrying clay slurry and uprooted trees over NH-27. Highway and rail culvert submerged.',
    reporterName: 'Biplab Debbarma',
    reporterPhone: '+91 94350 44556',
    reporterRole: 'ROLE_CITIZEN',
    status: 'VERIFIED',
    verifiedBy: 'EE NHIDCL Haflong',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    roadBlocked: true,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-2.jpg',
  },
  {
    id: 3,
    latitude: 25.1220,
    longitude: 93.0420,
    locationDescription: 'NH-54E Ghat near Jatinga Viewpoint, Assam',
    districtId: 'IN-AS-DH',
    landslideType: 'ROCKFALL',
    severity: 'SEVERE',
    description: 'Large fractured shale and sandstone boulders rolled down steep cut slope onto highway shoulder.',
    reporterName: 'Sub-Inspector D. Thaosen',
    reporterPhone: '+91 94350 28192',
    reporterRole: 'ROLE_FIELD_OFFICER',
    status: 'VERIFIED',
    verifiedBy: 'District Admin Dima Hasao',
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-3.jpg',
  },
  {
    id: 4,
    latitude: 25.5240,
    longitude: 91.8840,
    locationDescription: 'Wahkhen Ghat Cut Section km 18, SH-01, Meghalaya',
    districtId: 'IN-ML-EKH',
    landslideType: 'TENSION_CRACK',
    severity: 'SEVERE',
    description: 'Fresh longitudinal tension crack 15cm wide observed along cut slope above village houses. High risk of progressive failure.',
    reporterName: 'K. Nongrum (Resident)',
    reporterPhone: '+91 98621 55678',
    reporterRole: 'ROLE_CITIZEN',
    status: 'VERIFIED',
    verifiedBy: 'SDRF Officer T. Sangma',
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-4.jpg',
  },
  {
    id: 5,
    latitude: 25.2974,
    longitude: 91.5828,
    locationDescription: 'Mawsynram Ridge Road km 8, Meghalaya',
    districtId: 'IN-ML-EKH',
    landslideType: 'SOIL_SLIDE',
    severity: 'SEVERE',
    description: 'Steep road embankment failure with heavy mud slump encroaching outer road edge after non-stop monsoon downpour.',
    reporterName: 'P. Marbaniang',
    reporterPhone: '+91 97740 66778',
    reporterRole: 'ROLE_CITIZEN',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-5.jpg',
  },
  {
    id: 6,
    latitude: 25.1050,
    longitude: 92.8650,
    locationDescription: 'Harangajao Valley Rail & Road Link, Assam',
    districtId: 'IN-AS-DH',
    landslideType: 'DEBRIS_FLOW',
    severity: 'CATASTROPHIC',
    description: 'Valley toe erosion triggered sudden mudflow inundating access road to railway yard. Evacuation advised.',
    reporterName: 'G. Sengyung',
    reporterPhone: '+91 94351 88990',
    reporterRole: 'ROLE_FIELD_OFFICER',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
    roadBlocked: true,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-6.jpg',
  },
  {
    id: 7,
    latitude: 27.3520,
    longitude: 88.6200,
    locationDescription: 'Burtuk Steep Gorge, NH-10 Highway, Sikkim',
    districtId: 'IN-SK-GTK',
    landslideType: 'ROCKFALL',
    severity: 'SEVERE',
    description: 'Retaining wall damaged by rolling boulders and rockfall near helipad bypass. One-way traffic piloted.',
    reporterName: 'Karma Lepcha (Traffic SDRF)',
    reporterPhone: '+91 94340 12345',
    reporterRole: 'ROLE_FIELD_OFFICER',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 7).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-7.jpg',
  },
  {
    id: 8,
    latitude: 25.3090,
    longitude: 91.8950,
    locationDescription: 'Pynursla Ridge Sector km 22, SH-01, Meghalaya',
    districtId: 'IN-ML-EKH',
    landslideType: 'ROAD_SUBSIDENCE',
    severity: 'MODERATE',
    description: 'Road surface sank 25cm along 30m stretch following drainage overflow. Heavy trucks restricted.',
    reporterName: 'B. Khongwir',
    reporterPhone: '+91 98630 44321',
    reporterRole: 'ROLE_CITIZEN',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 8).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-8.jpg',
  },
  {
    id: 9,
    latitude: 25.6720,
    longitude: 94.1050,
    locationDescription: 'Dzüdza Bridge Approach, NH-29, Kohima, Nagaland',
    districtId: 'IN-NL-KHM',
    landslideType: 'ROAD_SUBSIDENCE',
    severity: 'SEVERE',
    description: 'Outer lane road subsidence of 40cm near culvert km 42. Heavy freight diverted via Jotsoma bypass.',
    reporterName: 'Kevi Angami (Traffic Officer)',
    reporterPhone: '+91 94360 77889',
    reporterRole: 'ROLE_FIELD_OFFICER',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 9).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-9.jpg',
  },
  {
    id: 10,
    latitude: 27.2880,
    longitude: 88.5860,
    locationDescription: 'Ranipool River Bank Sector, Gangtok, Sikkim',
    districtId: 'IN-SK-GTK',
    landslideType: 'SOIL_SLIDE',
    severity: 'MODERATE',
    description: 'Active soil slump on riverbank flank encroaching pedestrian pathway and power line pole.',
    reporterName: 'Tenzing Bhutia',
    reporterPhone: '+91 98320 65432',
    reporterRole: 'ROLE_CITIZEN',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 10).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-10.jpg',
  },
  {
    id: 11,
    latitude: 23.4750,
    longitude: 93.3280,
    locationDescription: 'Champhai - Zokhawthar Border Highway km 14, Mizoram',
    districtId: 'IN-MZ-CHM',
    landslideType: 'SOIL_SLIDE',
    severity: 'MINOR',
    description: 'Small mudslide deposited soil on roadway verge. Single lane operational with caution.',
    reporterName: 'Lalringzuala',
    reporterPhone: '+91 98625 78901',
    reporterRole: 'ROLE_CITIZEN',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 11).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-11.jpg',
  },
  {
    id: 12,
    latitude: 25.1667,
    longitude: 93.0167,
    locationDescription: 'Haflong Hill Cut Colony Ward 4, Dima Hasao, Assam',
    districtId: 'IN-AS-DH',
    landslideType: 'TENSION_CRACK',
    severity: 'SEVERE',
    description: 'Multiple parallel tension cracks opened across upper slope above 20 residential homes. Immediate evacuation ordered.',
    reporterName: 'R. Thaosen (Ward Member)',
    reporterPhone: '+91 94355 23456',
    reporterRole: 'ROLE_FIELD_OFFICER',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 12).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-12.jpg',
  },
  {
    id: 13,
    latitude: 25.4950,
    longitude: 91.8840,
    locationDescription: 'Nongkrem Hills Escarpment, Meghalaya',
    districtId: 'IN-ML-EKH',
    landslideType: 'SOIL_SLIDE',
    severity: 'MODERATE',
    description: 'Terrace soil failure along agricultural slopes. Mud deposited on rural feeder track.',
    reporterName: 'D. Syiem',
    reporterPhone: '+91 98632 11099',
    reporterRole: 'ROLE_CITIZEN',
    status: 'PENDING_VERIFICATION',
    timestamp: new Date(Date.now() - 3600000 * 13).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-13.jpg',
  },
  {
    id: 14,
    latitude: 27.3150,
    longitude: 88.5990,
    locationDescription: 'Tadong 5th Mile Ridge, Sikkim',
    districtId: 'IN-SK-GTK',
    landslideType: 'SOIL_SLIDE',
    severity: 'MINOR',
    description: 'Small earth slip on upper cut slope near educational institution campus. Drain cleared.',
    reporterName: 'Passang Dorjee',
    reporterPhone: '+91 97330 87654',
    reporterRole: 'ROLE_CITIZEN',
    status: 'RESOLVED',
    timestamp: new Date(Date.now() - 3600000 * 14).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-14.jpg',
  },
  {
    id: 15,
    latitude: 25.6750,
    longitude: 94.1020,
    locationDescription: 'Kohima Local Ground Valley Verge, Nagaland',
    districtId: 'IN-NL-KHM',
    landslideType: 'ROAD_SUBSIDENCE',
    severity: 'MODERATE',
    description: 'Masonry storm drain cracked and slope shifted 15cm downhill towards valley houses.',
    reporterName: 'Neibou Sekhose',
    reporterPhone: '+91 94364 32109',
    reporterRole: 'ROLE_CITIZEN',
    status: 'PENDING_VERIFICATION',
    timestamp: new Date(Date.now() - 3600000 * 15).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-15.jpg',
  },
  {
    id: 16,
    latitude: 25.3000,
    longitude: 93.1600,
    locationDescription: 'Maibang Old Town Bypass Road, Dima Hasao, Assam',
    districtId: 'IN-AS-DH',
    landslideType: 'ROCKFALL',
    severity: 'MODERATE',
    description: 'Multiple sharp boulders detached from sandstone cliff and fell onto single-lane arterial road.',
    reporterName: 'H. Langthasa',
    reporterPhone: '+91 94352 99887',
    reporterRole: 'ROLE_FIELD_OFFICER',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 16).toISOString(),
    roadBlocked: false,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-16.jpg',
  },
  {
    id: 17,
    latitude: 25.2014,
    longitude: 91.9056,
    locationDescription: 'Mawlynnong Escarpment Trail, Meghalaya',
    districtId: 'IN-ML-EKH',
    landslideType: 'DEBRIS_FLOW',
    severity: 'SEVERE',
    description: 'Surface runoff overflowed natural gorge creating sudden debris avalanche across footpath and tourist viewpoint access.',
    reporterName: 'W. Khongngai',
    reporterPhone: '+91 98623 45678',
    reporterRole: 'ROLE_CITIZEN',
    status: 'VERIFIED',
    timestamp: new Date(Date.now() - 3600000 * 17).toISOString(),
    roadBlocked: true,
    casualtiesReported: 0,
    mediaUrl: '/report-photo-17.jpg',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 1,
    identifier: 'IN-NDMA-CAP-2026-DH-001',
    sender: 'ddma-dima-hasao@assam.gov.in',
    sentAt: new Date(Date.now() - 1800000).toISOString(),
    status: 'Actual',
    msgType: 'Alert',
    scope: 'Public',
    category: 'Geo',
    event: 'Flash Landslide & Debris Flow Red Alert',
    urgency: 'Immediate',
    severity: 'Extreme',
    certainty: 'Observed',
    headline: 'CRITICAL HAZARD: Massive Mudslides on NH-27 Haflong-Lumding Section',
    description: 'Torrential rainfall exceeding 112mm in 24 hours has triggered widespread slope instability and debris flows across Dima Hasao. Major road artery NH-27 is blocked at Dihangi and Jatinga.',
    instruction: 'All travelers must halt travel toward Haflong. Residents in Haflong Hill Cut Colony and Harangajao Valley must immediately move to designated government relief shelters.',
    districtId: 'IN-AS-DH',
    affectedAreaName: 'Dima Hasao (Haflong, Jatinga, Harangajao, Dihangi)',
    language: 'en',
    dispatchedChannels: 'SMS_GATEWAY,FCM_PUSH,NDMA_CAP_FEED,AIR_RADIO',
    recipientsCount: 42500,
    capXml: '<?xml version="1.0" encoding="UTF-8"?><alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">...</alert>',
  },
  {
    id: 2,
    identifier: 'IN-NDMA-CAP-2026-EKH-002',
    sender: 'ddma-east-khasi-hills@meghalaya.gov.in',
    sentAt: new Date(Date.now() - 7200000).toISOString(),
    status: 'Actual',
    msgType: 'Alert',
    scope: 'Public',
    category: 'Geo',
    event: 'High Slope Instability & Tension Crack Warning',
    urgency: 'Expected',
    severity: 'Severe',
    certainty: 'Likely',
    headline: 'WARNING: Active Slope Instability on SH-01 Shillong-Dawki Highway',
    description: 'Intense precipitation in Sohra and Pynursla belts has saturated soil horizons. Tension cracks observed along Wahkhen ghat cut slope.',
    instruction: 'Night vehicular movement prohibited along SH-01. Heavy vehicles diverted via Umkiang.',
    districtId: 'IN-ML-EKH',
    affectedAreaName: 'East Khasi Hills (Sohra, Pynursla, Dawki Corridor)',
    language: 'en',
    dispatchedChannels: 'SMS_GATEWAY,FCM_PUSH,CAP_FEED',
    recipientsCount: 38200,
  },
];

export const mockOverviewStats: Record<string, OverviewStats> = {
  'IN-ML-EKH': {
    districtId: 'IN-ML-EKH',
    districtName: 'East Khasi Hills (Shillong)',
    state: 'Meghalaya',
    currentRiskLevel: 'HIGH',
    triggerStatus: 'WARNING',
    rainfall24hMm: 78.5,
    rainfall3dMm: 215.0,
    rainfall7dMm: 440.0,
    highRiskVillagesCount: 3,
    blockedRoadsCount: 1,
    pendingIncidentReportsCount: 2,
    activeAlertsCount: 1,
    emergencyHelpline: '1077 / 0364-2222277',
    lastUpdated: new Date().toISOString(),
  },
  'IN-AS-DH': {
    districtId: 'IN-AS-DH',
    districtName: 'Dima Hasao (Haflong)',
    state: 'Assam',
    currentRiskLevel: 'VERY_HIGH',
    triggerStatus: 'ALERT',
    rainfall24hMm: 112.0,
    rainfall3dMm: 320.0,
    rainfall7dMm: 610.0,
    highRiskVillagesCount: 5,
    blockedRoadsCount: 2,
    pendingIncidentReportsCount: 4,
    activeAlertsCount: 2,
    emergencyHelpline: '1077 / 03673-236222',
    lastUpdated: new Date().toISOString(),
  },
  'IN-SK-GTK': {
    districtId: 'IN-SK-GTK',
    districtName: 'Gangtok',
    state: 'Sikkim',
    currentRiskLevel: 'MODERATE',
    triggerStatus: 'WATCH',
    rainfall24hMm: 45.0,
    rainfall3dMm: 120.0,
    rainfall7dMm: 250.0,
    highRiskVillagesCount: 1,
    blockedRoadsCount: 0,
    pendingIncidentReportsCount: 1,
    activeAlertsCount: 0,
    emergencyHelpline: '1070 / 03592-202720',
    lastUpdated: new Date().toISOString(),
  },
  'IN-MZ-CHM': {
    districtId: 'IN-MZ-CHM',
    districtName: 'Champhai',
    state: 'Mizoram',
    currentRiskLevel: 'LOW',
    triggerStatus: 'NORMAL',
    rainfall24hMm: 32.0,
    rainfall3dMm: 95.0,
    rainfall7dMm: 180.0,
    highRiskVillagesCount: 0,
    blockedRoadsCount: 0,
    pendingIncidentReportsCount: 0,
    activeAlertsCount: 0,
    emergencyHelpline: '1077 / 03831-234200',
    lastUpdated: new Date().toISOString(),
  },
  'IN-NL-KHM': {
    districtId: 'IN-NL-KHM',
    districtName: 'Kohima',
    state: 'Nagaland',
    currentRiskLevel: 'HIGH',
    triggerStatus: 'WARNING',
    rainfall24hMm: 54.0,
    rainfall3dMm: 145.0,
    rainfall7dMm: 290.0,
    highRiskVillagesCount: 2,
    blockedRoadsCount: 1,
    pendingIncidentReportsCount: 2,
    activeAlertsCount: 1,
    emergencyHelpline: '1077 / 0370-2290022',
    lastUpdated: new Date().toISOString(),
  },
};
