package com.pahaarsaathi.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "landslide_reports")
public class LandslideReport {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private Double latitude;

    @Column(nullable = false)
    private Double longitude;

    @Column
    private String locationDescription;

    @Column
    private String districtId;

    @Column(nullable = false)
    private String landslideType = "SOIL_SLIDE"; // DEBRIS_FLOW, ROCKFALL, SOIL_SLIDE, ROAD_SUBSIDENCE, TENSION_CRACK

    @Column(nullable = false)
    private String severity = "MODERATE"; // MINOR, MODERATE, SEVERE, CATASTROPHIC

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column
    private String mediaUrl; // Photo / video uploaded to MinIO

    @Column
    private String mediaThumbnailUrl;

    @Column
    private String reporterName;

    @Column
    private String reporterPhone;

    @Column
    private String reporterRole = "CITIZEN"; // CITIZEN, FIELD_OFFICER

    @Column
    private String status = "PENDING_VERIFICATION"; // PENDING_VERIFICATION, VERIFIED, RESOLVED, REJECTED

    @Column
    private String verifiedBy;

    @Column
    private String offlineSyncId; // UUID generated by PWA IndexedDB when reported offline

    @Column(nullable = false)
    private LocalDateTime timestamp = LocalDateTime.now();

    @Column
    private Boolean roadBlocked = false;

    @Column
    private Integer casualtiesReported = 0;

    public LandslideReport() {}

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Double getLatitude() { return latitude; }
    public void setLatitude(Double latitude) { this.latitude = latitude; }

    public Double getLongitude() { return longitude; }
    public void setLongitude(Double longitude) { this.longitude = longitude; }

    public String getLocationDescription() { return locationDescription; }
    public void setLocationDescription(String locationDescription) { this.locationDescription = locationDescription; }

    public String getDistrictId() { return districtId; }
    public void setDistrictId(String districtId) { this.districtId = districtId; }

    public String getLandslideType() { return landslideType; }
    public void setLandslideType(String landslideType) { this.landslideType = landslideType; }

    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getMediaUrl() { return mediaUrl; }
    public void setMediaUrl(String mediaUrl) { this.mediaUrl = mediaUrl; }

    public String getMediaThumbnailUrl() { return mediaThumbnailUrl; }
    public void setMediaThumbnailUrl(String mediaThumbnailUrl) { this.mediaThumbnailUrl = mediaThumbnailUrl; }

    public String getReporterName() { return reporterName; }
    public void setReporterName(String reporterName) { this.reporterName = reporterName; }

    public String getReporterPhone() { return reporterPhone; }
    public void setReporterPhone(String reporterPhone) { this.reporterPhone = reporterPhone; }

    public String getReporterRole() { return reporterRole; }
    public void setReporterRole(String reporterRole) { this.reporterRole = reporterRole; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getVerifiedBy() { return verifiedBy; }
    public void setVerifiedBy(String verifiedBy) { this.verifiedBy = verifiedBy; }

    public String getOfflineSyncId() { return offlineSyncId; }
    public void setOfflineSyncId(String offlineSyncId) { this.offlineSyncId = offlineSyncId; }

    public LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }

    public Boolean getRoadBlocked() { return roadBlocked; }
    public void setRoadBlocked(Boolean roadBlocked) { this.roadBlocked = roadBlocked; }

    public Integer getCasualtiesReported() { return casualtiesReported; }
    public void setCasualtiesReported(Integer casualtiesReported) { this.casualtiesReported = casualtiesReported; }
}
